### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by MS012086** [TUMFTM/ScenarioArchitect#1]
Hello, 

When scenario entity to be drawn portion is selected with "bound_l & bound_r" a track is defined by a left and right bound, when I select veh_1 creating the path then following error message received.

How to resolve this error?

** (python3:6731): WARNING **: 15:45:01.457: AT-SPI: Could not obtain desktop path or name

** (python3:6731): WARNING **: 15:45:01.477: atk-bridge: get_device_events_reply: unknown signature

** (python3:6731): WARNING **: 15:45:01.477: atk-bridge: get_device_events_reply: unknown signature

** (python3:6731): WARNING **: 15:45:01.477: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (python3:6731): WARNING **: 15:45:01.479: AT-SPI: Could not obtain desktop path or name

** (python3:6731): WARNING **: 15:45:01.479: AT-SPI: Could not obtain desktop path or name

** (python3:6731): WARNING **: 15:45:01.479: AT-SPI: Could not obtain desktop path or name

** (python3:6731): WARNING **: 15:45:01.484: AT-SPI: Could not obtain desktop path or name

** (python3:6731): WARNING **: 15:45:01.488: AT-SPI: Could not obtain desktop path or name

** (python3:6731): WARNING **: 15:45:01.489: AT-SPI: Could not obtain desktop path or name

Segmentation fault (core dumped)

Tested:
Ubuntu 18.04
Python 3.6.9

**Comment by StahlTim** [comment]
These error message(s) have not occurred for me personally and do not indicate a cause/source in the code.

Does the error always occur consistently for one and the same action?

**Comment by MS012086** [comment]
Hello Mr.StahlTim,

Does the error always occur consistently for one and the same action?
Yes.
I have deleted the entire package and downloaded the package again, while creating the scenario observed the same error ( Segmentation fault (core dumped).

Thanks & Regards,
Saravanan

**Comment by StahlTim** [comment]
By "consistent" I mean, does the error always occur with the same operation (e.g. clicking on a certain button or similar)?

Only in such a case can I try to understand and address the problem. If the problem occurs at different times / actions, I rather suspect a system-related cause.

**Comment by StahlTim** [comment]
Closed due to inactivity
